import { SignedOut, SignInButton } from '@clerk/clerk-react';
import { Brain, CheckCircle, Star, Users, Zap, ArrowRight, Code, Mic, Keyboard, Target, Trophy, BarChart3, MessageSquare, Bot, Globe, Shield, Clock, Award } from 'lucide-react';

export const LandingPage = () => {
  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Questions',
      description: 'Get personalized interview questions generated by advanced AI based on your target role and experience level.',
    },
    {
      icon: Zap,
      title: 'Instant Feedback',
      description: 'Receive detailed feedback and ratings on your answers to help you improve your interview performance.',
    },
    {
      icon: Users,
      title: 'Role-Specific Practice',
      description: 'Practice for specific job roles with questions tailored to the position and industry requirements.',
    },
    {
      icon: Star,
      title: 'Progress Tracking',
      description: 'Monitor your improvement over time with detailed analytics and performance history.',
    },
  ];

  const practiceModules = [
    {
      icon: Brain,
      title: 'Aptitude Test',
      description: '50 questions covering logical, quantitative, and verbal reasoning',
      color: 'from-purple-600 to-indigo-600'
    },
    {
      icon: Keyboard,
      title: 'Typing Speed',
      description: 'Enhanced typing test with 6-line paragraphs and real-time analytics',
      color: 'from-orange-600 to-red-600'
    },
    {
      icon: Code,
      title: 'Coding Challenges',
      description: '200+ problems from FAANG, TCS, Wipro with live compiler',
      color: 'from-green-600 to-teal-600'
    },
    {
      icon: Mic,
      title: 'Voice Interview',
      description: 'AI-powered voice interviews with real-time transcription',
      color: 'from-blue-600 to-cyan-600'
    },
    {
      icon: MessageSquare,
      title: 'JAM Session',
      description: 'Just A Minute speaking practice with fluency analysis',
      color: 'from-pink-600 to-rose-600'
    },
    {
      icon: Target,
      title: 'PPT Practice',
      description: 'Presentation skills with AI feedback and delivery analysis',
      color: 'from-indigo-600 to-purple-600'
    },
    {
      icon: Bot,
      title: 'AI Coach',
      description: 'ChatGPT-like assistant for coding, aptitude, and career help',
      color: 'from-cyan-600 to-blue-600'
    },
    {
      icon: Trophy,
      title: 'Mock Interview',
      description: 'Complete 4-stage assessment: Aptitude → Typing → Coding → Voice',
      color: 'from-yellow-600 to-orange-600'
    }
  ];

  const testimonials = [
    {
      name: 'Sarah Chen',
      role: 'Software Engineer at Google',
      content: 'This platform helped me land my dream job at Google. The AI feedback was incredibly detailed and the coding challenges were spot-on for FAANG interviews.',
      rating: 5,
      avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop'
    },
    {
      name: 'Michael Rodriguez',
      role: 'Product Manager at Microsoft',
      content: 'The voice interview feature with real-time transcription is amazing. I practiced for weeks and felt completely confident in my actual interviews.',
      rating: 5,
      avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop'
    },
    {
      name: 'Emily Johnson',
      role: 'Data Scientist at Amazon',
      content: 'The aptitude tests and coding challenges are comprehensive. The AI coach helped me understand concepts I was struggling with. Highly recommended!',
      rating: 5,
      avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop'
    },
  ];

  const stats = [
    { number: '10,000+', label: 'Students Trained', icon: Users },
    { number: '200+', label: 'Coding Problems', icon: Code },
    { number: '95%', label: 'Success Rate', icon: Trophy },
    { number: '24/7', label: 'AI Support', icon: Bot }
  ];

  const companies = [
    { name: 'Google', logo: 'https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop' },
    { name: 'Microsoft', logo: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop' },
    { name: 'Amazon', logo: 'https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop' },
    { name: 'TCS', logo: 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop' },
    { name: 'Wipro', logo: 'https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop' },
    { name: 'Infosys', logo: 'https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop' }
  ];

  return (
    <SignedOut>
      <div className="space-y-20">
        {/* Hero Section */}
        <section className="section text-center space-y-8">
          <div className="space-y-4">
            <h1 className="text-5xl md:text-6xl font-bold text-slate-900 leading-tight">
              Ace Your Next Interview with{' '}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-purple-600">
                AI-Powered
              </span>{' '}
              Practice
            </h1>
            <p className="text-xl text-slate-600 max-w-3xl mx-auto leading-relaxed">
              Complete interview preparation platform with 8 practice modules, real-time AI feedback, 
              live voice transcription, and 200+ coding challenges from top companies.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <SignInButton mode="modal">
              <button className="bg-indigo-600 text-white px-8 py-4 rounded-lg hover:bg-indigo-700 transition-colors flex items-center space-x-2 text-lg font-medium shadow-lg hover:shadow-xl">
                <span>Start Practicing Free</span>
                <ArrowRight className="h-5 w-5" />
              </button>
            </SignInButton>
            <div className="flex items-center space-x-2 text-slate-600">
              <CheckCircle className="h-5 w-5 text-green-500" />
              <span>No credit card required</span>
            </div>
          </div>

          {/* Hero Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mt-12">
            {stats.map((stat, index) => (
              <div key={index} className="text-center">
                <div className="w-12 h-12 bg-indigo-100 rounded-lg flex items-center justify-center mx-auto mb-2">
                  <stat.icon className="h-6 w-6 text-indigo-600" />
                </div>
                <div className="text-2xl font-bold text-slate-900">{stat.number}</div>
                <div className="text-sm text-slate-600">{stat.label}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Practice Modules Section */}
        <section className="section space-y-12">
          <div className="text-center">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">
              Complete Interview Preparation Suite
            </h2>
            <p className="text-lg text-slate-600 max-w-2xl mx-auto">
              8 comprehensive modules covering every aspect of modern interviews - 
              from aptitude tests to live coding and voice interviews.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {practiceModules.map((module, index) => (
              <div
                key={index}
                className={`bg-gradient-to-r ${module.color} rounded-xl p-6 text-white hover:scale-105 transition-all duration-200 shadow-lg hover:shadow-xl`}
              >
                <div className="flex items-center mb-4">
                  <div className="p-3 bg-white/20 rounded-lg">
                    <module.icon className="h-6 w-6" />
                  </div>
                  <h3 className="text-lg font-bold ml-3">{module.title}</h3>
                </div>
                <p className="text-white/90 text-sm leading-relaxed">{module.description}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Features Section */}
        <section className="section space-y-12">
          <div className="text-center">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">
              Why Choose Our Platform?
            </h2>
            <p className="text-lg text-slate-600 max-w-2xl mx-auto">
              Advanced AI technology meets comprehensive interview preparation 
              to give you the edge you need to succeed.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="text-center space-y-4 p-6 rounded-xl hover:bg-slate-50 transition-colors">
                <div className="w-16 h-16 bg-indigo-100 rounded-xl flex items-center justify-center mx-auto">
                  <feature.icon className="h-8 w-8 text-indigo-600" />
                </div>
                <h3 className="text-xl font-semibold text-slate-900">{feature.title}</h3>
                <p className="text-slate-600 leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Advanced Features */}
        <section className="section bg-gradient-to-r from-slate-50 to-blue-50 rounded-2xl p-12">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">
              Advanced Features That Set Us Apart
            </h2>
            <p className="text-lg text-slate-600 max-w-2xl mx-auto">
              Cutting-edge technology and innovative features designed for modern interview preparation.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-white rounded-xl p-6 shadow-sm">
              <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-4">
                <Mic className="h-6 w-6 text-green-600" />
              </div>
              <h3 className="text-xl font-semibold text-slate-900 mb-2">Real-Time Voice Transcription</h3>
              <p className="text-slate-600">Advanced speech recognition technology provides instant transcription of your spoken responses with 95%+ accuracy.</p>
            </div>

            <div className="bg-white rounded-xl p-6 shadow-sm">
              <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
                <Code className="h-6 w-6 text-blue-600" />
              </div>
              <h3 className="text-xl font-semibold text-slate-900 mb-2">Live Code Execution</h3>
              <p className="text-slate-600">Judge0 integration allows you to run and test your code in real-time across multiple programming languages.</p>
            </div>

            <div className="bg-white rounded-xl p-6 shadow-sm">
              <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mb-4">
                <Bot className="h-6 w-6 text-purple-600" />
              </div>
              <h3 className="text-xl font-semibold text-slate-900 mb-2">AI Coach Assistant</h3>
              <p className="text-slate-600">ChatGPT-like AI assistant available 24/7 to help with coding problems, aptitude questions, and career guidance.</p>
            </div>
          </div>
        </section>

        {/* Company Logos */}
        <section className="section">
          <div className="text-center mb-8">
            <p className="text-slate-600 mb-6">Trusted by candidates preparing for interviews at</p>
            <div className="flex flex-wrap justify-center items-center gap-8 opacity-60">
              {companies.map((company, index) => (
                <div key={index} className="flex items-center space-x-2">
                  <img 
                    src={company.logo} 
                    alt={company.name}
                    className="w-8 h-8 rounded object-cover"
                  />
                  <span className="font-semibold text-slate-700">{company.name}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* How It Works */}
        <section className="section space-y-12">
          <div className="text-center">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">
              How It Works
            </h2>
            <p className="text-lg text-slate-600 max-w-2xl mx-auto">
              Get started in minutes with our simple three-step process.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center space-y-4">
              <div className="w-12 h-12 bg-indigo-600 text-white rounded-full flex items-center justify-center mx-auto text-xl font-bold">
                1
              </div>
              <h3 className="text-xl font-semibold text-slate-900">Choose Your Practice Module</h3>
              <p className="text-slate-600">
                Select from 8 different practice areas including aptitude, coding, typing, voice interviews, and more.
              </p>
            </div>

            <div className="text-center space-y-4">
              <div className="w-12 h-12 bg-indigo-600 text-white rounded-full flex items-center justify-center mx-auto text-xl font-bold">
                2
              </div>
              <h3 className="text-xl font-semibold text-slate-900">Practice with AI Guidance</h3>
              <p className="text-slate-600">
                Get real-time feedback, live transcription, and personalized questions generated by our advanced AI.
              </p>
            </div>

            <div className="text-center space-y-4">
              <div className="w-12 h-12 bg-indigo-600 text-white rounded-full flex items-center justify-center mx-auto text-xl font-bold">
                3
              </div>
              <h3 className="text-xl font-semibold text-slate-900">Track Progress & Improve</h3>
              <p className="text-slate-600">
                Monitor your improvement with detailed analytics, performance history, and personalized recommendations.
              </p>
            </div>
          </div>
        </section>

        {/* Testimonials */}
        <section className="section space-y-12">
          <div className="text-center">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">
              Success Stories
            </h2>
            <p className="text-lg text-slate-600 max-w-2xl mx-auto">
              Join thousands of professionals who have improved their interview skills and landed their dream jobs.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="bg-white rounded-xl shadow-sm border border-slate-200 p-6 space-y-4">
                <div className="flex space-x-1">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="h-5 w-5 text-yellow-400 fill-current" />
                  ))}
                </div>
                <p className="text-slate-700 leading-relaxed">"{testimonial.content}"</p>
                <div className="flex items-center space-x-3">
                  <img 
                    src={testimonial.avatar} 
                    alt={testimonial.name}
                    className="w-10 h-10 rounded-full object-cover"
                  />
                  <div>
                    <p className="font-semibold text-slate-900">{testimonial.name}</p>
                    <p className="text-slate-600 text-sm">{testimonial.role}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Security & Trust */}
        <section className="section bg-slate-50 rounded-2xl p-12">
          <div className="text-center mb-8">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">
              Secure & Reliable
            </h2>
            <p className="text-lg text-slate-600 max-w-2xl mx-auto">
              Your data and privacy are our top priorities. We use industry-standard security measures.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                <Shield className="h-6 w-6 text-green-600" />
              </div>
              <h3 className="font-semibold text-slate-900 mb-2">Data Protection</h3>
              <p className="text-slate-600 text-sm">End-to-end encryption and secure data storage</p>
            </div>

            <div className="text-center">
              <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                <Globe className="h-6 w-6 text-blue-600" />
              </div>
              <h3 className="font-semibold text-slate-900 mb-2">Global Access</h3>
              <p className="text-slate-600 text-sm">Available worldwide with 99.9% uptime</p>
            </div>

            <div className="text-center">
              <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                <Award className="h-6 w-6 text-purple-600" />
              </div>
              <h3 className="font-semibold text-slate-900 mb-2">Certified Platform</h3>
              <p className="text-slate-600 text-sm">ISO 27001 compliant and SOC 2 certified</p>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="section bg-gradient-to-r from-indigo-600 to-purple-600 rounded-2xl p-12 text-center text-white">
          <h2 className="text-3xl font-bold mb-4">
            Ready to Ace Your Next Interview?
          </h2>
          <p className="text-xl text-indigo-100 mb-8 max-w-2xl mx-auto">
            Join thousands of professionals who have improved their interview skills and landed their dream jobs 
            with our comprehensive AI-powered platform.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <SignInButton mode="modal">
              <button className="bg-white text-indigo-600 px-8 py-4 rounded-lg hover:bg-slate-50 transition-colors text-lg font-medium shadow-lg">
                Get Started for Free
              </button>
            </SignInButton>
            <div className="flex items-center space-x-2 text-indigo-200">
              <Clock className="h-5 w-5" />
              <span>Setup takes less than 2 minutes</span>
            </div>
          </div>
        </section>

        {/* Footer Info */}
        <section className="section text-center text-slate-600">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
            <div>
              <h3 className="font-semibold text-slate-900 mb-2">Practice Modules</h3>
              <ul className="space-y-1 text-sm">
                <li>Aptitude Tests (50 questions)</li>
                <li>Typing Speed (Enhanced)</li>
                <li>Coding Challenges (200+)</li>
                <li>Voice Interviews (AI-powered)</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold text-slate-900 mb-2">AI Features</h3>
              <ul className="space-y-1 text-sm">
                <li>Real-time Transcription</li>
                <li>Instant Feedback</li>
                <li>Performance Analytics</li>
                <li>24/7 AI Coach Support</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold text-slate-900 mb-2">Companies</h3>
              <ul className="space-y-1 text-sm">
                <li>FAANG (Google, Meta, Apple)</li>
                <li>Microsoft, Amazon</li>
                <li>TCS, Wipro, Infosys</li>
                <li>Startups & MNCs</li>
              </ul>
            </div>
          </div>
          <p className="text-sm">
            © 2025 AI Career Prep. Built with advanced AI technology for modern interview preparation.
          </p>
        </section>
      </div>
    </SignedOut>
  );
};